version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "CleanArch123"
    ports:
      - "1433:1433"
    networks:
      - mynetwork

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "8080:80"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=CleanArchSampleDb;User Id=sa;Password=CleanArch123;TrustServerCertificate=True;
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
